load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "mymath",
    srcs = ["my_cal.go", "my_math.go"],
    importpath = "mycompany.com/package_demo/a_package",
    visibility = ["//visibility:public"],
)